apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: pim-app
spec:
  environment: rhpam-production-immutable
  commonConfig:
    adminPassword: adminPassword
  objects:
    console:
      replicas: 0
    processMigration:
      database:
        type: postgresql
      image: pimserver-custom
      imageTag: latest
      env:
      ### LDAP CONFIGURATIONS
      - name: QUARKUS_SECURITY_LDAP_DIR_CONTEXT_PASSWORD
        value: secret
      - name: QUARKUS_SECURITY_LDAP_DIR_CONTEXT_URL
        value: ldap://my-ldap.example.com:389
      - name: QUARKUS_SECURITY_LDAP_DIR_CONTEXT_PRINCIPAL
        value: uid=admin,ou=system
      - name: QUARKUS_HTTP_AUTH_POLICY_MAIN_POLICY_ROLES_ALLOWED
        value: LDAP GROUP 01,LDAP GROUP 02
      - name: PIM_AUTH_METHOD
        value: ldap
      - name: QUARKUS_SECURITY_USERS_FILE_ENABLED
        value: "false"
      - name: QUARKUS_SECURITY_JDBC_ENABLED
        value: "false"
      #### KIE SERVERS CONFIGURATIONS FOR WRAPPER SCRIPT
      - name: KIE_SERVER_IMPORT_LIST
        value: ALL
      #### KIE SERVER ON THE SAME NAMESPACE (THE SERVICE_HOST AND SERVICE_PORT are automaticalli injected with their default value)
      - name: RHPAM_KIESERVER1_KIESERVER_PASSWORD
        value: kieserver_password
      - name: RHPAM_KIESERVER1_KIESERVER_USERNAME
        value: adminUser
      - name: RHPAM_KIESERVER2_KIESERVER_PASSWORD
        value: kieserver_password2
      - name: RHPAM_KIESERVER2_KIESERVER_USERNAME
        value: adminUser
      #### KIE SERVER ON ANOTHER NAMESPACE
      - name: RHPAM_KIESERVER3_SERVICE_HOST
        value: kie-server3.anothernamespace.svc.cluster.local
      - name: RHPAM_KIESERVER3_KIESERVER_SERVICE_PORT
        value: '8080' 
      - name: RHPAM_KIESERVER3_KIESERVER_PASSWORD
        value: kieserver_password3
      - name: RHPAM_KIESERVER3_KIESERVER_USERNAME
        value: adminUser
    servers:
    - database:
        type: h2
      replicas: 0
