apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: rhpam-pim
spec:
  environment: rhpam-production
  objects:
    console:
      replicas: 0
    processMigration:
      database:
        type: postgresql
      image: pimserver-custom
      imageTag: latest
    servers:
    - replicas: 0
